A = "10";
B = "20";
console.log("Before swap :");
console.log("A = ", A);
console.log("B = ", B);
var temp = A;
A = B;
B = temp;
console.log("After  swap :");
console.log("A = ", A);
console.log("B = ", B);
