var MyFullName;
console.log(MyFullName);
MyFullName = "Dipti Shelavene";
console.log(MyFullName);
MyFullName = "Dipti Dattatray Shelavane";
console.log(MyFullName);
var MyLove = "I love only JS ";
console.log(MyLove);
var firstName = "Dipti";
var lastName = "Shelavane";
var Age = "20";
var Address = "Solapur";
var gender = "Female";
var Marital_status = "N0";
console.log("first name : ", firstName);
console.log("last name : ", lastName);
console.log("Age : ", Age);
console.log("Address : ", Address);
console.log("Gender : ", gender);
console.log("Marital status : ", Marital_status);
